### ISSUE TITLE
Cannot type capital letters in TextField

### ISSUE THREAD

**Issue by midwan** [mythsman/guisan#1]
Even when testing in the included Examples, the TextField does not seem to accept capital letters.
Using Shift (LShift or RShift) and/or Caps Lock, we always get small case letters instead.

To recreate:
- compile the included examples
- run `sdlwidgets`
- try to type capital letters in a TextField

**Comment by mythsman** [comment]
Frankly speaking ... you have to implement that function yourself , because it is a simple framework just for educational purpose ...
